/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'team-members': TeamMember;
    testimonials: Testimonial;
    'faq-items': FaqItem;
    'client-logos': ClientLogo;
    'brand-assets': BrandAsset;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'faq-items': FaqItemsSelect<false> | FaqItemsSelect<true>;
    'client-logos': ClientLogosSelect<false> | ClientLogosSelect<true>;
    'brand-assets': BrandAssetsSelect<false> | BrandAssetsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    branding: Branding;
    'site-settings': SiteSetting;
    'design-tokens': DesignToken;
    typography: Typography;
    'layout-motion': LayoutMotion;
    stats: Stat;
    home: Home;
    'about-page': AboutPage;
    'team-page': TeamPage;
    'contact-page': ContactPage;
    'why-real-numbers-page': WhyRealNumbersPage;
    'our-expertise-page': OurExpertisePage;
    'use-cases-page': UseCasesPage;
    'questions-founders-ask-page': QuestionsFoundersAskPage;
  };
  globalsSelect: {
    branding: BrandingSelect<false> | BrandingSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'design-tokens': DesignTokensSelect<false> | DesignTokensSelect<true>;
    typography: TypographySelect<false> | TypographySelect<true>;
    'layout-motion': LayoutMotionSelect<false> | LayoutMotionSelect<true>;
    stats: StatsSelect<false> | StatsSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'team-page': TeamPageSelect<false> | TeamPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'why-real-numbers-page': WhyRealNumbersPageSelect<false> | WhyRealNumbersPageSelect<true>;
    'our-expertise-page': OurExpertisePageSelect<false> | OurExpertisePageSelect<true>;
    'use-cases-page': UseCasesPageSelect<false> | UseCasesPageSelect<true>;
    'questions-founders-ask-page': QuestionsFoundersAskPageSelect<false> | QuestionsFoundersAskPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role: string;
  photo?: (number | null) | Media;
  bio: string;
  /**
   * Shown only for the two leadership cards (e.g. "B.A. in Accounting...").
   */
  education?: string | null;
  leadership?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  name: string;
  /**
   * e.g. "CEO, Compete". Leave blank if none.
   */
  role?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items".
 */
export interface FaqItem {
  id: number;
  question: string;
  answer: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-logos".
 */
export interface ClientLogo {
  id: number;
  name: string;
  logo: number | Media;
  /**
   * Where clicking the logo should go, if anywhere.
   */
  href?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Downloadable brand files shown on the Brand Identity page — logo packs, icon/numeral sets, fonts, templates. Source originals live in the Drive brand folder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-assets".
 */
export interface BrandAsset {
  id: number;
  title: string;
  category: 'logos' | 'icons' | 'numerals' | 'colors' | 'fonts' | 'photography' | 'animations' | 'documents' | 'social';
  /**
   * One line shown under the title on the Brand Identity page.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faq-items';
        value: number | FaqItem;
      } | null)
    | ({
        relationTo: 'client-logos';
        value: number | ClientLogo;
      } | null)
    | ({
        relationTo: 'brand-assets';
        value: number | BrandAsset;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  bio?: T;
  education?: T;
  leadership?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  role?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-logos_select".
 */
export interface ClientLogosSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  href?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-assets_select".
 */
export interface BrandAssetsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide logo files and footer copyright line.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding".
 */
export interface Branding {
  id: number;
  /**
   * Dark logo, shown on light backgrounds (header).
   */
  headerLogo?: (number | null) | Media;
  /**
   * Off-white logo, shown on the dark footer.
   */
  footerLogo?: (number | null) | Media;
  footerCopyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Sitewide info used when a page doesn't set its own — favicon, default social share image, default meta description, and whether search engines can index the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Used after the page title, e.g. "About | Real Numbers".
   */
  siteName?: string | null;
  /**
   * A short one-line description of the business — used as the fallback meta description when a page doesn't set its own.
   */
  tagline?: string | null;
  /**
   * The small icon shown in browser tabs. A square image works best (512×512px or larger).
   */
  favicon?: (number | null) | Media;
  /**
   * Shown when a page is shared on social media and hasn't set its own share image, e.g. via WhatsApp, LinkedIn, or Facebook.
   */
  defaultOgImage?: (number | null) | Media;
  /**
   * Keep this off while the site is still in progress — turn it on when ready to go live, so Google and other search engines start showing the site in results.
   */
  searchEngineIndexing?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site-wide brand colors — changes apply everywhere immediately, no redeploy needed. Handle with care: these are the core brand palette used across every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-tokens".
 */
export interface DesignToken {
  id: number;
  colors?: {
    /**
     * Hex color, e.g. #b85840.
     */
    black?: string | null;
    /**
     * Hex color, e.g. #b85840.
     */
    offwhite?: string | null;
    /**
     * Hex color, e.g. #b85840.
     */
    white?: string | null;
    /**
     * Hex color, e.g. #b85840.
     */
    red?: string | null;
    /**
     * Hex color, e.g. #b85840.
     */
    redDark?: string | null;
    /**
     * Hex color, e.g. #b85840.
     */
    blue?: string | null;
    /**
     * Hex color, e.g. #b85840.
     */
    blueDark?: string | null;
    /**
     * Hex color, e.g. #b85840.
     */
    stone?: string | null;
    /**
     * Hex color, e.g. #b85840.
     */
    horizon?: string | null;
    /**
     * Hex color, e.g. #b85840.
     */
    clay?: string | null;
    /**
     * Hex color, e.g. #b85840.
     */
    jet?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Shared text styles used everywhere on the site — change one here and every heading/paragraph using it updates together, so the site stays visually consistent. These aren't per-field overrides on purpose: individually resizing every single paragraph would make the site look inconsistent fast.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "typography".
 */
export interface Typography {
  id: number;
  h1?: {
    /**
     * 1 = smallest, 3 = default (current site design), 5 = largest. Scales the existing responsive size up or down — stays fluid on mobile either way.
     */
    sizeScale?: ('1' | '2' | '3' | '4' | '5') | null;
    /**
     * Space between lines of text. Default: 0.92. Lower = tighter, higher = airier.
     */
    lineHeight?: number | null;
    /**
     * Space between letters, in em. Default: -0.035. Negative = tighter, positive = wider.
     */
    letterSpacing?: number | null;
    weight?: ('400' | '500' | '600' | '700' | '800') | null;
  };
  h2?: {
    /**
     * 1 = smallest, 3 = default (current site design), 5 = largest. Scales the existing responsive size up or down — stays fluid on mobile either way.
     */
    sizeScale?: ('1' | '2' | '3' | '4' | '5') | null;
    /**
     * Space between lines of text. Default: 1. Lower = tighter, higher = airier.
     */
    lineHeight?: number | null;
    /**
     * Space between letters, in em. Default: -0.028. Negative = tighter, positive = wider.
     */
    letterSpacing?: number | null;
    weight?: ('400' | '500' | '600' | '700' | '800') | null;
  };
  h3?: {
    /**
     * 1 = smallest, 3 = default (current site design), 5 = largest. Scales the existing responsive size up or down — stays fluid on mobile either way.
     */
    sizeScale?: ('1' | '2' | '3' | '4' | '5') | null;
    /**
     * Space between lines of text. Default: 1.15. Lower = tighter, higher = airier.
     */
    lineHeight?: number | null;
    /**
     * Space between letters, in em. Default: -0.016. Negative = tighter, positive = wider.
     */
    letterSpacing?: number | null;
    weight?: ('400' | '500' | '600' | '700' | '800') | null;
  };
  eyebrow?: {
    /**
     * 1 = smallest, 3 = default (current site design), 5 = largest. Scales the existing responsive size up or down — stays fluid on mobile either way.
     */
    sizeScale?: ('1' | '2' | '3' | '4' | '5') | null;
    /**
     * Space between lines of text. Default: 1.333. Lower = tighter, higher = airier.
     */
    lineHeight?: number | null;
    /**
     * Space between letters, in em. Default: 0.14. Negative = tighter, positive = wider.
     */
    letterSpacing?: number | null;
    weight?: ('400' | '500' | '600' | '700' | '800') | null;
  };
  lede?: {
    /**
     * 1 = smallest, 3 = default (current site design), 5 = largest. Scales the existing responsive size up or down — stays fluid on mobile either way.
     */
    sizeScale?: ('1' | '2' | '3' | '4' | '5') | null;
    /**
     * Space between lines of text. Default: 1.5. Lower = tighter, higher = airier.
     */
    lineHeight?: number | null;
    /**
     * Space between letters, in em. Default: 0. Negative = tighter, positive = wider.
     */
    letterSpacing?: number | null;
    weight?: ('400' | '500' | '600' | '700' | '800') | null;
  };
  body?: {
    /**
     * 1 = smallest, 3 = default (current site design), 5 = largest. Scales the existing responsive size up or down — stays fluid on mobile either way.
     */
    sizeScale?: ('1' | '2' | '3' | '4' | '5') | null;
    /**
     * Space between lines of text. Default: 1.625. Lower = tighter, higher = airier.
     */
    lineHeight?: number | null;
    /**
     * Space between letters, in em. Default: 0. Negative = tighter, positive = wider.
     */
    letterSpacing?: number | null;
    weight?: ('400' | '500' | '600' | '700' | '800') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site-wide structural and motion controls. Each of these affects every page at once.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "layout-motion".
 */
export interface LayoutMotion {
  id: number;
  /**
   * How wide the main content area is on desktop screens. Doesn't affect mobile.
   */
  containerWidth?: ('80' | '86' | '92' | '96' | '100') | null;
  /**
   * How rounded cards, photos, and form fields are. Buttons stay fully round regardless — that's a deliberate brand shape, not affected by this.
   */
  cornerRoundness?: ('0' | '50' | '100' | '150' | '200') | null;
  /**
   * How much breathing room is between sections and elements site-wide.
   */
  spacingDensity?: ('80' | '90' | '100' | '115' | '130') | null;
  /**
   * How fast hover effects, reveals, and transitions play across the site.
   */
  motionSpeed?: ('150' | '125' | '100' | '75' | '50') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Homepage "Proof in numbers" section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats".
 */
export interface Stat {
  id: number;
  heading?: string | null;
  stats?:
    | {
        label: string;
        value: number;
        color: 'red' | 'blue' | 'jet' | 'horizon';
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Home page copy. Drag the section rows below to reorder the page. Testimonials, stats, and client logos are managed in their own collections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * Drag the handle on each row to reorder sections on the live page. Header and footer aren't listed here — they're the same on every page.
   */
  sections?:
    (HeroBlock | DifferenceBlock | StatsBlock | DividerBlock | CtaDarkBlock | AudienceBlock | StoriesBlock)[] | null;
  /**
   * Optional — controls what shows in the browser tab, search results, and when this page is shared on social media. Leave blank to use the site default.
   */
  seo?: {
    /**
     * Shown in the browser tab and as the search-result headline.
     */
    title?: string | null;
    /**
     * The snippet shown under the title in search results.
     */
    description?: string | null;
    /**
     * Shown when this page is shared on social media. Falls back to the site default in Site Settings.
     */
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Words that cycle after "Real" in the headline, e.g. "Numbers.", "Clarity.", "Confidence."
   */
  rotatingWords?:
    | {
        word: string;
        id?: string | null;
      }[]
    | null;
  description: string;
  primaryCtaLabel?: string | null;
  secondaryCtaLabel?: string | null;
  featuredPhoto?: {
    heading?: string | null;
    ctaLabel?: string | null;
    /**
     * Photos used in the rotating slideshow behind the heading.
     */
    images?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  logosStrip?: {
    /**
     * The logos themselves come from the Client Logos collection, not here.
     */
    ctaLabel?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DifferenceBlock".
 */
export interface DifferenceBlock {
  heading?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'diff';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DividerBlock".
 */
export interface DividerBlock {
  /**
   * Decorative full-width strip. MP4 recommended. Plays muted, on loop, with a fixed background effect. Leave empty to show the default image instead.
   */
  video?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'divider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaDarkBlock".
 */
export interface CtaDarkBlock {
  heading?: string | null;
  ctaLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AudienceBlock".
 */
export interface AudienceBlock {
  /**
   * "One partnership for every stage of growth" — dark navy section.
   */
  heading?: string | null;
  areas?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'audience';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StoriesBlock".
 */
export interface StoriesBlock {
  /**
   * Testimonials themselves come from the Testimonials collection, not here.
   */
  eyebrow?: string | null;
  heading?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stories';
}
/**
 * About page copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    heading: string;
    lede: string;
  };
  ourStory?: {
    heading?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Upload one photo for a static image, or several for an auto-playing fading slideshow.
     */
    photos?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
    photoCaption?: string | null;
  };
  whatWeBelieve?: {
    heading?: string | null;
    intro?: string | null;
    principles?:
      | {
          lead: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  howWeWork?: {
    heading?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Short-form bios for the About page — the full-length bios live on the Team page (Team Members collection).
   */
  leadership?: {
    heading?: string | null;
    cards?:
      | {
          name: string;
          role: string;
          bio: string;
          id?: string | null;
        }[]
      | null;
    note?: string | null;
    teamLinkLabel?: string | null;
  };
  /**
   * Optional — controls what shows in the browser tab, search results, and when this page is shared on social media. Leave blank to use the site default.
   */
  seo?: {
    /**
     * Shown in the browser tab and as the search-result headline.
     */
    title?: string | null;
    /**
     * The snippet shown under the title in search results.
     */
    description?: string | null;
    /**
     * Shown when this page is shared on social media. Falls back to the site default in Site Settings.
     */
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Team page copy. The roster itself lives in the Team Members collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-page".
 */
export interface TeamPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    heading: string;
    lede?: string | null;
  };
  sectionHeading?: string | null;
  closingCta: {
    heading: string;
    closingLine?: string | null;
    buttonLabel?: string | null;
  };
  /**
   * Optional — controls what shows in the browser tab, search results, and when this page is shared on social media. Leave blank to use the site default.
   */
  seo?: {
    /**
     * Shown in the browser tab and as the search-result headline.
     */
    title?: string | null;
    /**
     * The snippet shown under the title in search results.
     */
    description?: string | null;
    /**
     * Shown when this page is shared on social media. Falls back to the site default in Site Settings.
     */
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contact page copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    heading: string;
  };
  /**
   * "Prefer a direct conversation?" links beside the form.
   */
  directContact?: {
    label?: string | null;
    /**
     * Digits only, with country code, e.g. 972523735059.
     */
    whatsappNumber?: string | null;
    email?: string | null;
  };
  manifesto: {
    heading: string;
    text?: string | null;
  };
  /**
   * Optional — controls what shows in the browser tab, search results, and when this page is shared on social media. Leave blank to use the site default.
   */
  seo?: {
    /**
     * Shown in the browser tab and as the search-result headline.
     */
    title?: string | null;
    /**
     * The snippet shown under the title in search results.
     */
    description?: string | null;
    /**
     * Shown when this page is shared on social media. Falls back to the site default in Site Settings.
     */
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Why Real Numbers page copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "why-real-numbers-page".
 */
export interface WhyRealNumbersPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    heading: string;
    ledeParagraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  whyChooseUs?: {
    heading?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The 4-card grid (Startup Mindset, Strategic Thinking, Hands-on Partnership, Built for Long-Term Growth).
   */
  valueProps?:
    | {
        title: string;
        paragraph1: string;
        paragraph2?: string | null;
        id?: string | null;
      }[]
    | null;
  whatMakesDifferent?: {
    heading?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Upload one photo for a static image, or several for an auto-playing fading slideshow.
     */
    photos?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  closingCta: {
    heading: string;
    closingLine?: string | null;
    buttonLabel?: string | null;
  };
  /**
   * Optional — controls what shows in the browser tab, search results, and when this page is shared on social media. Leave blank to use the site default.
   */
  seo?: {
    /**
     * Shown in the browser tab and as the search-result headline.
     */
    title?: string | null;
    /**
     * The snippet shown under the title in search results.
     */
    description?: string | null;
    /**
     * Shown when this page is shared on social media. Falls back to the site default in Site Settings.
     */
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Our Expertise page copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-expertise-page".
 */
export interface OurExpertisePage {
  id: number;
  hero: {
    eyebrow?: string | null;
    heading: string;
    ledeParagraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Financial Operations, Strategic Finance, Fundraising & Growth, Business Performance.
   */
  areas?:
    | {
        title: string;
        tagline: string;
        paragraphs?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        /**
         * The pill list under each area (e.g. "Bookkeeping", "Payroll").
         */
        services?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * "One integrated financial partnership" closing section.
   */
  integrated?: {
    heading?: string | null;
    text?: string | null;
    /**
     * Upload one photo for a static image, or several for an auto-playing fading slideshow.
     */
    photos?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
    photoCaption?: string | null;
  };
  closingCta: {
    heading: string;
    closingLine?: string | null;
    buttonLabel?: string | null;
  };
  /**
   * Optional — controls what shows in the browser tab, search results, and when this page is shared on social media. Leave blank to use the site default.
   */
  seo?: {
    /**
     * Shown in the browser tab and as the search-result headline.
     */
    title?: string | null;
    /**
     * The snippet shown under the title in search results.
     */
    description?: string | null;
    /**
     * Shown when this page is shared on social media. Falls back to the site default in Site Settings.
     */
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Use Cases page copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "use-cases-page".
 */
export interface UseCasesPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    heading: string;
    lede?: string | null;
  };
  /**
   * Upload one photo for a static image, or several for an auto-playing fading slideshow.
   */
  atmospherePhotos?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  atmospherePhotoCaption?: string | null;
  situationsIntro?: string | null;
  situations?:
    | {
        /**
         * Written as a founder quote, e.g. "We're growing faster than our financial infrastructure."
         */
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  closingCta: {
    heading: string;
    buttonLabel?: string | null;
  };
  /**
   * Optional — controls what shows in the browser tab, search results, and when this page is shared on social media. Leave blank to use the site default.
   */
  seo?: {
    /**
     * Shown in the browser tab and as the search-result headline.
     */
    title?: string | null;
    /**
     * The snippet shown under the title in search results.
     */
    description?: string | null;
    /**
     * Shown when this page is shared on social media. Falls back to the site default in Site Settings.
     */
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Questions Founders Ask page copy. The Q&A list itself lives in the FAQ Items collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions-founders-ask-page".
 */
export interface QuestionsFoundersAskPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    heading: string;
  };
  /**
   * Upload one photo for a static image, or several for an auto-playing fading slideshow.
   */
  atmospherePhotos?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional — controls what shows in the browser tab, search results, and when this page is shared on social media. Leave blank to use the site default.
   */
  seo?: {
    /**
     * Shown in the browser tab and as the search-result headline.
     */
    title?: string | null;
    /**
     * The snippet shown under the title in search results.
     */
    description?: string | null;
    /**
     * Shown when this page is shared on social media. Falls back to the site default in Site Settings.
     */
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding_select".
 */
export interface BrandingSelect<T extends boolean = true> {
  headerLogo?: T;
  footerLogo?: T;
  footerCopyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  favicon?: T;
  defaultOgImage?: T;
  searchEngineIndexing?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-tokens_select".
 */
export interface DesignTokensSelect<T extends boolean = true> {
  colors?:
    | T
    | {
        black?: T;
        offwhite?: T;
        white?: T;
        red?: T;
        redDark?: T;
        blue?: T;
        blueDark?: T;
        stone?: T;
        horizon?: T;
        clay?: T;
        jet?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "typography_select".
 */
export interface TypographySelect<T extends boolean = true> {
  h1?:
    | T
    | {
        sizeScale?: T;
        lineHeight?: T;
        letterSpacing?: T;
        weight?: T;
      };
  h2?:
    | T
    | {
        sizeScale?: T;
        lineHeight?: T;
        letterSpacing?: T;
        weight?: T;
      };
  h3?:
    | T
    | {
        sizeScale?: T;
        lineHeight?: T;
        letterSpacing?: T;
        weight?: T;
      };
  eyebrow?:
    | T
    | {
        sizeScale?: T;
        lineHeight?: T;
        letterSpacing?: T;
        weight?: T;
      };
  lede?:
    | T
    | {
        sizeScale?: T;
        lineHeight?: T;
        letterSpacing?: T;
        weight?: T;
      };
  body?:
    | T
    | {
        sizeScale?: T;
        lineHeight?: T;
        letterSpacing?: T;
        weight?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "layout-motion_select".
 */
export interface LayoutMotionSelect<T extends boolean = true> {
  containerWidth?: T;
  cornerRoundness?: T;
  spacingDensity?: T;
  motionSpeed?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats_select".
 */
export interface StatsSelect<T extends boolean = true> {
  heading?: T;
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        color?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        diff?: T | DifferenceBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        divider?: T | DividerBlockSelect<T>;
        cta?: T | CtaDarkBlockSelect<T>;
        audience?: T | AudienceBlockSelect<T>;
        stories?: T | StoriesBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  rotatingWords?:
    | T
    | {
        word?: T;
        id?: T;
      };
  description?: T;
  primaryCtaLabel?: T;
  secondaryCtaLabel?: T;
  featuredPhoto?:
    | T
    | {
        heading?: T;
        ctaLabel?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  logosStrip?:
    | T
    | {
        ctaLabel?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DifferenceBlock_select".
 */
export interface DifferenceBlockSelect<T extends boolean = true> {
  heading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DividerBlock_select".
 */
export interface DividerBlockSelect<T extends boolean = true> {
  video?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaDarkBlock_select".
 */
export interface CtaDarkBlockSelect<T extends boolean = true> {
  heading?: T;
  ctaLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AudienceBlock_select".
 */
export interface AudienceBlockSelect<T extends boolean = true> {
  heading?: T;
  areas?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StoriesBlock_select".
 */
export interface StoriesBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        lede?: T;
      };
  ourStory?:
    | T
    | {
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        photos?:
          | T
          | {
              image?: T;
              id?: T;
            };
        photoCaption?: T;
      };
  whatWeBelieve?:
    | T
    | {
        heading?: T;
        intro?: T;
        principles?:
          | T
          | {
              lead?: T;
              text?: T;
              id?: T;
            };
      };
  howWeWork?:
    | T
    | {
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  leadership?:
    | T
    | {
        heading?: T;
        cards?:
          | T
          | {
              name?: T;
              role?: T;
              bio?: T;
              id?: T;
            };
        note?: T;
        teamLinkLabel?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-page_select".
 */
export interface TeamPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        lede?: T;
      };
  sectionHeading?: T;
  closingCta?:
    | T
    | {
        heading?: T;
        closingLine?: T;
        buttonLabel?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
      };
  directContact?:
    | T
    | {
        label?: T;
        whatsappNumber?: T;
        email?: T;
      };
  manifesto?:
    | T
    | {
        heading?: T;
        text?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "why-real-numbers-page_select".
 */
export interface WhyRealNumbersPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        ledeParagraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  whyChooseUs?:
    | T
    | {
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  valueProps?:
    | T
    | {
        title?: T;
        paragraph1?: T;
        paragraph2?: T;
        id?: T;
      };
  whatMakesDifferent?:
    | T
    | {
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        photos?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  closingCta?:
    | T
    | {
        heading?: T;
        closingLine?: T;
        buttonLabel?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "our-expertise-page_select".
 */
export interface OurExpertisePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        ledeParagraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  areas?:
    | T
    | {
        title?: T;
        tagline?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        services?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  integrated?:
    | T
    | {
        heading?: T;
        text?: T;
        photos?:
          | T
          | {
              image?: T;
              id?: T;
            };
        photoCaption?: T;
      };
  closingCta?:
    | T
    | {
        heading?: T;
        closingLine?: T;
        buttonLabel?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "use-cases-page_select".
 */
export interface UseCasesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        lede?: T;
      };
  atmospherePhotos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  atmospherePhotoCaption?: T;
  situationsIntro?: T;
  situations?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  closingCta?:
    | T
    | {
        heading?: T;
        buttonLabel?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions-founders-ask-page_select".
 */
export interface QuestionsFoundersAskPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
      };
  atmospherePhotos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}